import '@/styles/globals.scss';
import { ThemeProvider } from 'styled-components';
import theme from '@/styles/theme';
import { NotificationContextProvider } from '@/store/notificationContext';
import type { AppProps } from 'next/app';
import Layout from '@/components/layout/Layout';
import Head from 'next/head';
export default function App({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider theme={theme}>
      <NotificationContextProvider>
        <Layout>
          <Head>
            <title>Dev/Dominat!on</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} />
        </Layout>
      </NotificationContextProvider>
    </ThemeProvider>
  );
}
