import ContactForm from '@/components/contact/ContactForm';
import Head from 'next/head';
const ContactPage = () => {
  return (
    <>
      <Head>
        <title>Contact Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactForm />
    </>
  );
};

export default ContactPage;
