import Head from 'next/head';
import Hero from '@/components/homePage/Hero';
import FeaturedPosts from '@/components/homePage/FeaturedPosts';
export default function Home() {
  return (
    <>
      <Head>
        <title>NEXT-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>This is the NEXT-BLOG APP</h1>
      <Hero />
      <FeaturedPosts />
    </>
  );
}
