import Head from 'next/head';
import Hero from '@/components/homePage/Hero';
import FeaturedPosts from '@/components/homePage/FeaturedPosts';
import { getFeaturedPosts } from '@/helpers/posts-util';
export default function Home(props: any) {
  return (
    <>
      <Head>
        <title>NEXT-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <FeaturedPosts posts={props.posts} />
    </>
  );
}

export const getStaticProps = () => {
  const FeaturedPosts = getFeaturedPosts();

  return {
    props: {
      posts: FeaturedPosts,
    },
    revalidate: 1800,
  };
};
